import type { Property, PropertyUpsertPayload } from "@/types/domain"

/** Maps an API property row into the upsert form shape (create/update modals). */
export function propertyToUpsertPayload(item: Property): PropertyUpsertPayload {
  return {
    title: item.title,
    slug: item.slug,
    description: item.description,
    description_secondary: item.description_secondary,
    property_type: item.property_type,
    property_channel: item.property_channel,
    land_sale_mode: item.land_sale_mode,
    total_blocks: item.total_blocks,
    available_blocks: item.available_blocks,
    price_per_block: item.price_per_block,
    whole_land_price: item.whole_land_price,
    share_price: item.share_price,
    total_shares: item.total_shares,
    available_shares: item.available_shares,
    min_shares_per_order: item.min_shares_per_order,
    location_name: item.location_name,
    latitude: item.latitude,
    longitude: item.longitude,
    video_url: item.video_url,
    top_view_image: item.top_view_image,
    gallery_images: item.gallery_images ?? [],
    amenities: item.amenities ?? [],
    tags: item.tags ?? [],
    floor_plans: item.floor_plans ?? [],
    build_year: item.build_year,
    bedrooms: item.bedrooms,
    bathrooms: item.bathrooms,
    flat_label: item.flat_label ?? "",
    size_sqft: item.size_sqft,
    for_rent: item.for_rent,
    for_sale: item.for_sale,
    contact_website: item.contact_website,
    rating_average: item.rating_average,
    review_count: item.review_count,
    review_sample_author: item.review_sample_author,
    review_sample_date: item.review_sample_date,
    review_sample_text: item.review_sample_text,
    status: item.status,
    listing_active: item.listing_active !== false,
    expected_profit_percent: item.expected_profit_percent,
    investment_window_start: item.investment_window_start,
    investment_window_end: item.investment_window_end,
    share_investment_options: item.share_investment_options ?? [],
    representative: item.representative,
    managed_by: item.managed_by,
  }
}
