from __future__ import annotations

"""
Django settings for rs_server project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from email.utils import formataddr
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / ".env")
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rkef2q^fi@+1-v0)+b_kc917q5)pk+2_u$5!m_^6mn3=!6s8mu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
CORS_ALLOW_ALL_ORIGINS = True

SECURE_SSL_REDIRECT = False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'rest_framework_simplejwt.token_blacklist',
    'apps.apps.AppsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rs_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rs_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / "static"   # REQUIRED for collectstatic

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# Plot booking application: up to four ~10 MB files (multipart).
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "apps.utils.exceptions.custom_exception_handler",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

REFERRAL_COMMISSION_PERCENT = 5

# Used for referral links, password-reset links, and welcome emails (no trailing slash).
FRONTEND_PUBLIC_URL = os.environ.get("FRONTEND_PUBLIC_URL", "http://127.0.0.1:5173")

# Optional absolute URL to logo image for emails when no local file is available (HTTPS CDN).
PUBLIC_BRAND_LOGO_URL = (os.environ.get("PUBLIC_BRAND_LOGO_URL") or "").strip()

# Optional absolute path to JPEG/PNG for Money Receipt PDF header (defaults include media/assets/navlogo.jpg).
MONEY_RECEIPT_LOGO_PATH: str | None = None

# Optional override for inline CID logo in transactional emails (same as EMAIL_HOST_USER_IMAGE).
_email_logo_raw = (
    os.environ.get("EMAIL_INLINE_LOGO_PATH")
    or os.environ.get("EMAIL_HOST_USER_IMAGE")
    or ""
).strip()
EMAIL_INLINE_LOGO_PATH: str | None = _email_logo_raw if _email_logo_raw else None

SPECTACULAR_SETTINGS = {
    "TITLE": "Real estate investment API",
    "DESCRIPTION": "API docs for the real estate investment platform.",
    "VERSION": "1.0.0",
}

# Email (SMTP). Set EMAIL_HOST_PASSWORD (and optionally overrides) via environment —
# never commit credentials. Spacemail: host mail.spacemail.com; common ports 465 (SSL)
# or 587 (STARTTLS).
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST", "mail.spacemail.com")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "465"))

def _env_bool(name: str) -> bool | None:
    raw = os.environ.get(name)
    if raw is None:
        return None
    return raw.lower() in ("1", "true", "yes", "on")


_tls = _env_bool("EMAIL_USE_TLS")
_ssl = _env_bool("EMAIL_USE_SSL")
if _tls is not None or _ssl is not None:
    EMAIL_USE_TLS = bool(_tls)
    EMAIL_USE_SSL = bool(_ssl)
else:
    if EMAIL_PORT == 587:
        EMAIL_USE_TLS, EMAIL_USE_SSL = True, False
    elif EMAIL_PORT == 465:
        EMAIL_USE_TLS, EMAIL_USE_SSL = False, True
    else:
        EMAIL_USE_TLS, EMAIL_USE_SSL = False, False

# Friendly From header for all outbound mail (forgot-password, OTP, transactional).
# DEFAULT_FROM_EMAIL / EMAIL_HOST_USER should be the bare address; display name from EMAIL_SENDER_NAME.
_email_addr = os.environ.get("DEFAULT_FROM_EMAIL") or EMAIL_HOST_USER or "webmaster@localhost"
_sender_name = (os.environ.get("EMAIL_SENDER_NAME", "Eurostar Group") or "").strip()
DEFAULT_FROM_EMAIL = formataddr((_sender_name, _email_addr)) if _sender_name else _email_addr
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Console logging for transactional email debugging. Set EMAIL_DEBUG=1 for full SMTP snapshots in logs.
_EMAIL_DEBUG_ENV = os.environ.get("EMAIL_DEBUG", "").lower() in ("1", "true", "yes", "on")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "mail_fmt": {"format": "%(levelname)s %(name)s: %(message)s"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "mail_fmt"},
    },
    "loggers": {
        "apps.services.mail": {
            "handlers": ["console"],
            "level": "DEBUG" if (DEBUG or _EMAIL_DEBUG_ENV) else "INFO",
            "propagate": False,
        },
        "apps.services.booking_emails": {
            "handlers": ["console"],
            "level": "DEBUG" if (DEBUG or _EMAIL_DEBUG_ENV) else "INFO",
            "propagate": False,
        },
        "apps.services.account_emails": {
            "handlers": ["console"],
            "level": "DEBUG" if (DEBUG or _EMAIL_DEBUG_ENV) else "INFO",
            "propagate": False,
        },
    },
}
