# Generated by Django 5.2.4 on 2026-03-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('investor', 'Investor'), ('representative', 'Representative')], default='investor', max_length=20),
        ),
    ]
