# Generated by Django 5.2.4 on 2026-03-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_property_representative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='type',
            field=models.CharField(choices=[('direct', 'Direct Buy'), ('installment', 'Installment'), ('fractional', 'Fractional (Legacy)')], max_length=20),
        ),
    ]
