# Generated by Django 5.2.4 on 2026-03-31 15:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def forwards_advertiser_to_agent(apps, schema_editor):
    UserProfile = apps.get_model("apps", "UserProfile")
    UserProfile.objects.filter(role="advertiser").update(role="agent")


def backwards_agent_to_advertiser(apps, schema_editor):
    UserProfile = apps.get_model("apps", "UserProfile")
    UserProfile.objects.filter(role="agent").update(role="advertiser")


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_userprofile_managed_by_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='shares_owned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='available_shares',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='build_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='contact_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description_secondary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_plans',
            field=models.JSONField(blank=True, default=list, help_text='List of {"title","image_url","description"} objects.'),
        ),
        migrations.AddField(
            model_name='property',
            name='for_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='for_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='land_sale_mode',
            field=models.CharField(choices=[('per_block', 'Per block (fractional blocks)'), ('whole_land', 'Whole land (single purchase)'), ('fractional_share', 'Fractional shares (fixed price per share)')], default='per_block', max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='min_shares_per_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='rating_average',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='review_sample_author',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='review_sample_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='review_sample_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='share_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Used when land_sale_mode is fractional_share.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='size_sqft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='total_shares',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='whole_land_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed price for entire remaining land when land_sale_mode is whole_land (optional).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text="Percent of referred investment amount credited as commission when this user's code is used.", max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investment',
            name='blocks_owned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_agent_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('investor', 'Investor'), ('representative', 'Representative'), ('agent', 'Agent')], default='investor', max_length=20),
        ),
        migrations.RunPython(forwards_advertiser_to_agent, backwards_agent_to_advertiser),
    ]
