# Generated by Django 5.2.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0007_property_land_sale_agent_referral"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="property_channel",
            field=models.CharField(
                choices=[("direct_buy", "Direct buy"), ("installment", "Installment")],
                default="direct_buy",
                help_text="Homepage lane: direct buy vs installment (independent of land_sale_mode).",
                max_length=20,
            ),
        ),
    ]
