# Generated by ChatGPT on 2026-04-02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0009_property_flat_label"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="managed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_properties",
                to=settings.AUTH_USER_MODEL,
                help_text="Agent assigned by representative to handle this property (optional).",
            ),
        ),
    ]

