# Generated by Django 5.2.4 on 2026-04-02 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_align_land_sale_mode_with_channel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='expected_profit_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected profit % shown to investors (optional).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='investment_window_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='investment_window_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_active',
            field=models.BooleanField(default=True, help_text='When False, hidden from public listings; reps/agents can still manage.'),
        ),
        migrations.AddField(
            model_name='property',
            name='share_investment_options',
            field=models.JSONField(blank=True, default=list, help_text='For share/installment: e.g. [{"amount": "5000.00", "duration_years": 3}, ...].'),
        ),
        migrations.CreateModel(
            name='InvestmentCheckoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending approvals'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('agent_approved', models.BooleanField(default=False)),
                ('representative_approved', models.BooleanField(default=False)),
                ('rejected_reason', models.CharField(blank=True, max_length=500)),
                ('investment_type', models.CharField(max_length=20)),
                ('duration_years', models.PositiveIntegerField(default=0)),
                ('blocks_owned', models.PositiveIntegerField(default=0)),
                ('shares_owned', models.PositiveIntegerField(default=0)),
                ('referral_code_used', models.CharField(blank=True, max_length=40)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_checkout_requests', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_checkout_requests', to='apps.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
