# Generated by Django 5.2.4 on 2026-04-02 18:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_rename_direct_buy_and_direct_to_plot_buy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='maturity_notified_at',
            field=models.DateTimeField(blank=True, help_text='Set when investor was notified that this position is eligible for profit payout.', null=True),
        ),
        migrations.CreateModel(
            name='InvestmentRedemptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('profit_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_payout', models.DecimalField(decimal_places=2, max_digits=14)),
                ('profit_percent_used', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Property expected profit % or investment ROI % used for calculation.', max_digits=7)),
                ('notes', models.TextField(blank=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=500)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemption_requests', to='apps.investment')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemption_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemption_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='apps_invest_status_4e328d_idx'), models.Index(fields=['investor', '-created_at'], name='apps_invest_investo_6f55c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('checkout_new', 'New investment request'), ('payment_new', 'New payment submitted'), ('payment_approved', 'Payment approved'), ('property_created', 'Property created'), ('installment_reminder', 'Installment reminder'), ('investment_mature', 'Investment matured'), ('investment_active', 'Investment started'), ('redemption_new', 'New payout request'), ('redemption_update', 'Payout request update')], max_length=40)),
                ('title', models.CharField(max_length=220)),
                ('body', models.TextField(blank=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='apps_userno_user_id_e9758f_idx'), models.Index(fields=['user', 'read_at'], name='apps_userno_user_id_95bfa8_idx')],
            },
        ),
    ]
