# Generated by Django 5.2.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0015_notifications_redemption_maturity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("superadmin", "Superadmin"),
                    ("investor", "Investor"),
                    ("representative", "Representative"),
                    ("agent", "Agent"),
                ],
                default="investor",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.TextField(
                help_text="Primary listing copy; may contain HTML from staff UIs (sanitize before public display).",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="description_secondary",
            field=models.TextField(
                blank=True,
                help_text="Optional secondary copy; may contain HTML from staff UIs (sanitize before public display).",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="floor_plans",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of {"title","image_url","description"} objects; description may include HTML (sanitize on output).',
            ),
        ),
    ]
