# Generated by Django 5.2.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0016_userprofile_superadmin_property_richtext_help"),
    ]

    operations = [
        migrations.AddField(
            model_name="kyctemplate",
            name="required_for_checkout",
            field=models.BooleanField(
                default=False,
                help_text="When active, investors must have an approved submission for this template before creating checkout requests.",
            ),
        ),
    ]
