# Generated by Django 6.0.3 on 2026-04-05 11:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_normalize_fractional_to_installment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_type', models.CharField(choices=[('one_percent_installment', '1% installment'), ('fifty_percent_installment', '50% installment')], max_length=40)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('contact_notes', models.TextField(blank=True)),
                ('referral_code_used', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='installment',
            name='investment',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='property',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='investment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='investment',
        ),
        migrations.RemoveField(
            model_name='investmentcheckoutrequest',
            name='investor',
        ),
        migrations.RemoveField(
            model_name='investmentcheckoutrequest',
            name='property',
        ),
        migrations.RemoveIndex(
            model_name='investmentredemptionrequest',
            name='apps_invest_status_4e328d_idx',
        ),
        migrations.RemoveIndex(
            model_name='investmentredemptionrequest',
            name='apps_invest_investo_6f55c2_idx',
        ),
        migrations.AlterUniqueTogether(
            name='kycfielddefinition',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='kycfielddefinition',
            name='template',
        ),
        migrations.RemoveField(
            model_name='userkycsubmission',
            name='template',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentlog',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='linked_payment',
        ),
        migrations.RemoveField(
            model_name='paymentlog',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referred_user',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='userkycsubmission',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='userkycsubmission',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='usernotification',
            name='apps_userno_user_id_e9758f_idx',
        ),
        migrations.RemoveIndex(
            model_name='usernotification',
            name='apps_userno_user_id_95bfa8_idx',
        ),
        migrations.RemoveField(
            model_name='property',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='property',
            name='available_blocks',
        ),
        migrations.RemoveField(
            model_name='property',
            name='available_shares',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='build_year',
        ),
        migrations.RemoveField(
            model_name='property',
            name='contact_website',
        ),
        migrations.RemoveField(
            model_name='property',
            name='expected_profit_percent',
        ),
        migrations.RemoveField(
            model_name='property',
            name='flat_label',
        ),
        migrations.RemoveField(
            model_name='property',
            name='floor_plans',
        ),
        migrations.RemoveField(
            model_name='property',
            name='for_rent',
        ),
        migrations.RemoveField(
            model_name='property',
            name='investment_window_end',
        ),
        migrations.RemoveField(
            model_name='property',
            name='investment_window_start',
        ),
        migrations.RemoveField(
            model_name='property',
            name='land_sale_mode',
        ),
        migrations.RemoveField(
            model_name='property',
            name='managed_by',
        ),
        migrations.RemoveField(
            model_name='property',
            name='min_shares_per_order',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price_per_block',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_channel',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='representative',
        ),
        migrations.RemoveField(
            model_name='property',
            name='share_investment_options',
        ),
        migrations.RemoveField(
            model_name='property',
            name='share_price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='size_sqft',
        ),
        migrations.RemoveField(
            model_name='property',
            name='total_blocks',
        ),
        migrations.RemoveField(
            model_name='property',
            name='total_shares',
        ),
        migrations.RemoveField(
            model_name='property',
            name='whole_land_price',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='managed_by',
        ),
        migrations.AddField(
            model_name='property',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, help_text='Agent responsible for this land listing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_land_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='installment_years',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Required when sale_type is installment: fixed repayment term in years.', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='land_area_sqft',
            field=models.PositiveIntegerField(blank=True, help_text='Land area in square feet (optional).', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='land_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Total price for the entire land parcel.', max_digits=14),
        ),
        migrations.AddField(
            model_name='property',
            name='sale_type',
            field=models.CharField(choices=[('land_buy', 'Land buy (full payment)'), ('installment', 'Installment (whole land, fixed term)')], default='land_buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_active',
            field=models.BooleanField(default=True, help_text='When False, hidden from public listings; staff can still manage.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='referral_commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Reserved for future referral rewards when a referred user books land.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('investor', 'Investor')], default='investor', max_length=20),
        ),
        migrations.AddField(
            model_name='landbooking',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landbooking',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='apps.property'),
        ),
        migrations.AddField(
            model_name='landbooking',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_land_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Installment',
        ),
        migrations.DeleteModel(
            name='InvestmentCheckoutRequest',
        ),
        migrations.RemoveField(
            model_name='investmentredemptionrequest',
            name='investment',
        ),
        migrations.RemoveField(
            model_name='investmentredemptionrequest',
            name='investor',
        ),
        migrations.RemoveField(
            model_name='investmentredemptionrequest',
            name='reviewed_by',
        ),
        migrations.DeleteModel(
            name='KycFieldDefinition',
        ),
        migrations.DeleteModel(
            name='KycTemplate',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentLog',
        ),
        migrations.DeleteModel(
            name='PaymentRequest',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
        migrations.DeleteModel(
            name='UserKycSubmission',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
        migrations.DeleteModel(
            name='InvestmentRedemptionRequest',
        ),
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
