# Generated by Django 6.0.3 on 2026-04-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_normalize_profile_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.JSONField(blank=True, default=list, help_text='List of strings, e.g. ["Road access", "Electricity"].'),
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='build_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='contact_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='flat_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_plans',
            field=models.JSONField(blank=True, default=list, help_text='List of {title, image_url, description?} for detail page floor plan tabs.'),
        ),
        migrations.AddField(
            model_name='property',
            name='for_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('commercial', 'Commercial'), ('land', 'Land')], default='land', help_text='Display category on the public detail page (defaults to land).', max_length=20),
        ),
    ]
