# Generated by Django 6.0.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0032_sitesettings_plot_buy_promo_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="land_sale_mode",
            field=models.CharField(
                choices=[
                    ("per_block", "Per block"),
                    ("whole_land", "Whole land"),
                    ("fractional_share", "Land share / fractional"),
                ],
                default="whole_land",
                help_text="Whole land / plot maps vs land-share (fractional) listings.",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="share_investment_options",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Allowed land-share tiers: [{"amount": "100000.00", "duration_years": 3}, ...].',
            ),
        ),
        migrations.AddField(
            model_name="landbooking",
            name="investment_option_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Land-share tier amount chosen by the investor (must match property tiers when set).",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="landbooking",
            name="investment_option_duration_years",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Land-share tier duration in years (must match property tiers when set).",
                null=True,
            ),
        ),
    ]
