# Generated by Django 6.0.3 on 2026-04-18 10:39

import apps.model.land_bookings
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0035_landbooking_application_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landbooking',
            name='application_data',
            field=models.JSONField(blank=True, default=dict, help_text='Extended plot-booking application (structured form answers).'),
        ),
        migrations.AlterField(
            model_name='landbooking',
            name='plan_type',
            field=models.CharField(choices=[('one_percent_installment', '1% installment'), ('fifty_percent_installment', '50% installment'), ('investment', 'Investment (non-installment)')], max_length=40),
        ),
        migrations.AlterField(
            model_name='landsharelisting',
            name='payment_options',
            field=models.JSONField(blank=True, default=list, help_text='Tiers, e.g. [{"amount":"2000.00","billing_period":"monthly"},{"amount":"50000.00","billing_period":"monthly"}]. billing_period: monthly|yearly|one_time'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='plot_buy_installment_slot_limit',
            field=models.PositiveIntegerField(default=100, help_text='1% and 50% installment plans apply only to buy-plot (plot buy) listings. Counts pending + accepted plot-buy bookings using those plans; set to 0 to allow none.'),
        ),
        migrations.CreateModel(
            name='LandBookingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('passport_photo_1', 'Passport photo 1'), ('passport_photo_2', 'Passport photo 2'), ('nid_or_id', 'NID or valid ID copy'), ('booking_money_receipt', 'Booking money receipt / proof')], max_length=40)),
                ('file', models.FileField(upload_to=apps.model.land_bookings._booking_attachment_upload_to)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_attachments', to='apps.landbooking')),
            ],
            options={
                'ordering': ['kind'],
                'constraints': [models.UniqueConstraint(fields=('booking', 'kind'), name='uniq_booking_attachment_kind')],
            },
        ),
    ]
