# Generated by Django 6.0.3 on 2026-04-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0036_land_booking_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landbookingattachment',
            name='kind',
            field=models.CharField(choices=[('passport_photo_1', 'Passport photo 1'), ('nid_or_id', 'NID or valid ID copy'), ('booking_money_receipt', 'Booking money receipt / proof')], max_length=40),
        ),
    ]
